name: Build Thunderstore ZIP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  zip-thunderstore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload Thunderstore Folder
        uses: actions/upload-artifact@v4
        with:
          name: Thunderstore
          path: Thunderstore
